var equiv = [
  {
    ref_gc: "72001",
    gc: "Dead White",
    ref_ga: "72701",
    ga: "Dead White",
    ref_cit: "22-57",
    cit: "White Scar",
    ref_old_cit: "61-54",
    old_cit: "Skull White",
    ref_reap: "9039",
    reap: "Pure White",
    ref_mc: "70951",
    mc: "White"
  },
  {
    ref_gc: "72002",
    gc: "White Primer",
    ref_ga: "",
    ga: "",
    ref_cit: "21-34",
    cit: "Ceramite White",
    ref_old_cit: "",
    old_cit: "",
    ref_reap: "9108",
    reap: "Primer",
    ref_mc: "70919",
    mc: "Foundation White"
  },
  {
    ref_gc: "72004",
    gc: "Elf Skintone",
    ref_ga: "72704",
    ga: "Elf Skintone",
    ref_cit: "22-37",
    cit: "Kislev Flesh",
    ref_old_cit: "61-23",
    old_cit: "Elf Flesh",
    ref_reap: "",
    reap: "",
    ref_mc: "70804",
    mc: "Beige Red"
  },
  {
    ref_gc: "72005",
    gc: "Moon Yellow",
    ref_ga: "72705",
    ga: "Moon Yellow",
    ref_cit: "",
    cit: "",
    ref_old_cit: "61-11",
    old_cit: "Bad Moon Yellow",
    ref_reap: "9095",
    reap: "Clear Yellow",
    ref_mc: "70949",
    mc: "Light Yellow"
  },
  {
    ref_gc: "72006",
    gc: "Sun Yellow",
    ref_ga: "72706",
    ga: "Sun Yellow",
    ref_cit: "22-02",
    cit: "Flash Gitz Yellow",
    ref_old_cit: "61-10",
    old_cit: "Sunburst Yellow",
    ref_reap: "9008",
    reap: "Sun Yellow",
    ref_mc: "70915",
    mc: "Deep Yellow"
  },
  {
    ref_gc: "72007",
    gc: "Gold Yellow",
    ref_ga: "72707",
    ga: "Gold Yellow",
    ref_cit: "22-01",
    cit: "Yriel Yellow",
    ref_old_cit: "61-09",
    old_cit: "Golden Yellow",
    ref_reap: "9007",
    reap: "Marigold Yellow",
    ref_mc: "70948",
    mc: "Golden Yellow"
  },
  {
    ref_gc: "72008",
    gc: "Orange Fire",
    ref_ga: "72708",
    ga: "Orange Fire*",
    ref_cit: "22-04",
    cit: "Fire Dragon Breath",
    ref_old_cit: "61-08",
    old_cit: "Fiery Orange",
    ref_reap: "9006",
    reap: "Fire Orange",
    ref_mc: "70911",
    mc: "Light Orange"
  },
  {
    ref_gc: "72009",
    gc: "Hot Orange",
    ref_ga: "72709",
    ga: "Hot Orange",
    ref_cit: "22-03",
    cit: "Troll Slayer Orange",
    ref_old_cit: "61-07",
    old_cit: "Blazing Orange",
    ref_reap: "9005",
    reap: "Phoenix Red",
    ref_mc: "70817",
    mc: "Scarlet"
  },
  {
    ref_gc: "72010",
    gc: "Bloody Red",
    ref_ga: "72710",
    ga: "Bloody Red*",
    ref_cit: "22-05",
    cit: "Evil Sunz Scarlet",
    ref_old_cit: "61-06",
    old_cit: "Blood Red",
    ref_reap: "9094",
    reap: "Clear Red",
    ref_mc: "70909",
    mc: "Vermillion"
  },
  {
    ref_gc: "72011",
    gc: "Gory Red",
    ref_ga: "72711",
    ga: "Gory Red",
    ref_cit: "22-07",
    cit: "Wazdakka Red",
    ref_old_cit: "61-05",
    old_cit: "Red Gore",
    ref_reap: "9135",
    reap: "Carnage Red",
    ref_mc: "70982",
    mc: "Cavalry Brown"
  },
  {
    ref_gc: "72012",
    gc: "Scarlet Red",
    ref_ga: "72712",
    ga: "Scarlet Red",
    ref_cit: "21-04",
    cit: "Khorne Red",
    ref_old_cit: "",
    old_cit: "",
    ref_reap: "",
    reap: "",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72013",
    gc: "Squid Pink",
    ref_ga: "72713",
    ga: "Squid Pink",
    ref_cit: "",
    cit: "",
    ref_old_cit: "61-29",
    old_cit: "Tentacle Pink",
    ref_reap: "",
    reap: "",
    ref_mc: "70958",
    mc: "Pink"
  },
  {
    ref_gc: "72014",
    gc: "Warlord Purple",
    ref_ga: "72714",
    ga: "Warlord Purple",
    ref_cit: "21-33",
    cit: "Screamer Pink",
    ref_old_cit: "61-28",
    old_cit: "Warlock Purple",
    ref_reap: "9027",
    reap: "Pale Violet Red",
    ref_mc: "70945",
    mc: "Magenta"
  },
  {
    ref_gc: "72015",
    gc: "Hexed Lichen",
    ref_ga: "",
    ga: "",
    ref_cit: "21-06",
    cit: "Daemonette Hide",
    ref_old_cit: "68-05",
    old_cit: "Hormag. Purple",
    ref_reap: "9022",
    reap: "Nights. Purple",
    ref_mc: "70811",
    mc: "Violet"
  },
  {
    ref_gc: "72016",
    gc: "Royal Purple",
    ref_ga: "",
    ga: "",
    ref_cit: "22-09",
    cit: "Xereus Purple",
    ref_old_cit: "61-27",
    old_cit: "Liche Purple",
    ref_reap: "9132",
    reap: "Clear Plum",
    ref_mc: "70810",
    mc: "Royal Purple"
  },
  {
    ref_gc: "72019",
    gc: "Night Blue",
    ref_ga: "",
    ga: "",
    ref_cit: "",
    cit: "",
    ref_old_cit: "61-30",
    old_cit: "Midnight Blue",
    ref_reap: "",
    reap: "",
    ref_mc: "70899",
    mc: "Dark Prus. Blue"
  },
  {
    ref_gc: "72020",
    gc: "Imperial Blue",
    ref_ga: "",
    ga: "",
    ref_cit: "21-07",
    cit: "Kantor Blue",
    ref_old_cit: "61-32",
    old_cit: "Regal Blue",
    ref_reap: "",
    reap: "",
    ref_mc: "70807",
    mc: "Oxford Blue*"
  },
  {
    ref_gc: "72021",
    gc: "Magic Blue",
    ref_ga: "72721",
    ga: "Magic Blue",
    ref_cit: "21-09",
    cit: "Caledor Sky",
    ref_old_cit: "61-34",
    old_cit: "Enchanted Blue",
    ref_reap: "",
    reap: "",
    ref_mc: "70930",
    mc: "Dark Blue"
  },
  {
    ref_gc: "72021",
    gc: "Magic Blue",
    ref_ga: "72721",
    ga: "Magic Blue",
    ref_cit: "22-17",
    cit: "Teclis Blue",
    ref_old_cit: "61-34",
    old_cit: "Enchanted Blue",
    ref_reap: "",
    reap: "",
    ref_mc: "70930",
    mc: "Dark Blue"
  },
  {
    ref_gc: "72022",
    gc: "Ultram. Blue",
    ref_ga: "72722",
    ga: "Ultram. Blue",
    ref_cit: "22-15",
    cit: "Altd. Guard Blue",
    ref_old_cit: "61-33",
    old_cit: "Ultramarine Blue",
    ref_reap: "",
    reap: "",
    ref_mc: "70925",
    mc: "Blue"
  },
  {
    ref_gc: "72023",
    gc: "Electric Blue",
    ref_ga: "72723",
    ga: "Electric Blue",
    ref_cit: "22-18",
    cit: "Lothern Blue",
    ref_old_cit: "61-36",
    old_cit: "Ice Blue",
    ref_reap: "",
    reap: "",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72024",
    gc: "Turquoise",
    ref_ga: "",
    ga: "",
    ref_cit: "22-19",
    cit: "Sotek Green",
    ref_old_cit: "61-37",
    old_cit: "Hawk Turquoise",
    ref_reap: "9077",
    reap: "Marine Teal",
    ref_mc: "70969",
    mc: "Park Green Flat"
  },
  {
    ref_gc: "72027",
    gc: "Scurvy Green",
    ref_ga: "",
    ga: "",
    ref_cit: "22-21",
    cit: "Kabalite Green",
    ref_old_cit: "61-45",
    old_cit: "Scaly Green",
    ref_reap: "9131",
    reap: "Clear Viridian",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72028",
    gc: "Dark Green",
    ref_ga: "",
    ga: "",
    ref_cit: "",
    cit: "",
    ref_old_cit: "61-38",
    old_cit: "Dark ang. Green",
    ref_reap: "9096",
    reap: "Clear Green",
    ref_mc: "70891",
    mc: "Intermed. Green"
  },
  {
    ref_gc: "72029",
    gc: "Sick Green",
    ref_ga: "72729",
    ga: "Sick Green",
    ref_cit: "22-23",
    cit: "Warpstone Glow",
    ref_old_cit: "61-39",
    old_cit: "Snot Green",
    ref_reap: "9096",
    reap: "Clear Green",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72030",
    gc: "Goblin Green",
    ref_ga: "72730",
    ga: "Goblin Green",
    ref_cit: "22-25",
    cit: "Warboss Green",
    ref_old_cit: "61-42",
    old_cit: "",
    ref_reap: "",
    reap: "Clear Green",
    ref_mc: "70967",
    mc: "Olive Green"
  },
  {
    ref_gc: "72031",
    gc: "Cam. Green",
    ref_ga: "",
    ga: "",
    ref_cit: "22-30",
    cit: "Elysian Green",
    ref_old_cit: "61-44",
    old_cit: "Camo Green",
    ref_reap: "",
    reap: "",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72032",
    gc: "Escorp. Green",
    ref_ga: "72732",
    ga: "Escorp. Green",
    ref_cit: "22-24",
    cit: "Moot Green",
    ref_old_cit: "61-40",
    old_cit: "Scorpion Green",
    ref_reap: "9012",
    reap: "Pale Green",
    ref_mc: "70942",
    mc: "Light Green"
  },
  {
    ref_gc: "72034",
    gc: "Bone White",
    ref_ga: "72734",
    ga: "Bone White",
    ref_cit: "22-32",
    cit: "Ushabti Bone",
    ref_old_cit: "61-17",
    old_cit: "Bleached Bone",
    ref_reap: "",
    reap: "",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72035",
    gc: "Dead Flesh",
    ref_ga: "72735",
    ga: "Dead Flesh*",
    ref_cit: "22-29",
    cit: "Nurgling Green",
    ref_old_cit: "61-43",
    old_cit: "Rotting Flesh",
    ref_reap: "9036",
    reap: "Pale Olive",
    ref_mc: "70884",
    mc: "Stone Grey"
  },
  {
    ref_gc: "72036",
    gc: "Bronze Flesht.",
    ref_ga: "72736",
    ga: "Bronze Flesht.",
    ref_cit: "22-39",
    cit: "Ungor Flesh",
    ref_old_cit: "61-22",
    old_cit: "Bronze Flesh",
    ref_reap: "",
    reap: "",
    ref_mc: "70804",
    mc: "Beige Red"
  },
  {
    ref_gc: "72037",
    gc: "Filthy Brown",
    ref_ga: "",
    ga: "",
    ref_cit: "22-42",
    cit: "Tau Light Ochre",
    ref_old_cit: "61-16",
    old_cit: "Vomit Brown",
    ref_reap: "9031",
    reap: "Tanned Leather",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72038",
    gc: "Scroful. Brown",
    ref_ga: "",
    ga: "",
    ref_cit: "21-02",
    cit: "Jokaero Orange",
    ref_old_cit: "68-02",
    old_cit: "Mach. Solar Oran.",
    ref_reap: "",
    reap: "",
    ref_mc: "70856",
    mc: "Ochre Brown"
  },
  {
    ref_gc: "72038",
    gc: "Scroful. Brown",
    ref_ga: "",
    ga: "",
    ref_cit: "22-38",
    cit: "Bestigor Flesh",
    ref_old_cit: "",
    old_cit: "",
    ref_reap: "",
    reap: "",
    ref_mc: "70860",
    mc: "M. Fleshtone"
  },
  {
    ref_gc: "72039",
    gc: "Plague Brown",
    ref_ga: "",
    ga: "",
    ref_cit: "22-44",
    cit: "Zamesi Desert",
    ref_old_cit: "61-15",
    old_cit: "Bubonic Brown",
    ref_reap: "9074",
    reap: "Palomino Gold",
    ref_mc: "70877",
    mc: "Gold Brown"
  },
  {
    ref_gc: "72040",
    gc: "Leather Brown",
    ref_ga: "72740",
    ga: "Leather Brown",
    ref_cit: "21-21",
    cit: "XV88",
    ref_old_cit: "61-14",
    old_cit: "Snakeb. Leather",
    ref_reap: "9073",
    reap: "Chestnut Gold",
    ref_mc: "70876",
    mc: "Brown Sand"
  },
  {
    ref_gc: "72040",
    gc: "Leather Brown",
    ref_ga: "72740",
    ga: "Leather Brown",
    ref_cit: "22-43",
    cit: "Balor Brown",
    ref_old_cit: "61-14",
    old_cit: "Snakeb. Leather",
    ref_reap: "9073",
    reap: "Chestnut Gold",
    ref_mc: "70876",
    mc: "Brown Sand"
  },
  {
    ref_gc: "72041",
    gc: "Dwarf Skin",
    ref_ga: "72741",
    ga: "Dwarf Skin",
    ref_cit: "21-19",
    cit: "Ratskin Flesh",
    ref_old_cit: "61-21",
    old_cit: "Dwarf Flesh",
    ref_reap: "9068",
    reap: "Rosy Skin",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72042",
    gc: "Parasite Brown",
    ref_ga: "",
    ga: "",
    ref_cit: "22-40",
    cit: "Skrag Brown",
    ref_old_cit: "",
    old_cit: "",
    ref_reap: "",
    reap: "",
    ref_mc: "70981",
    mc: "Orange Brown"
  },
  {
    ref_gc: "72043",
    gc: "Beasty Brown",
    ref_ga: "72743",
    ga: "Beasty Brown",
    ref_cit: "21-20",
    cit: "Mournf. Brown",
    ref_old_cit: "61-13",
    old_cit: "Bestial Brown",
    ref_reap: "9138",
    reap: "Intense Brown",
    ref_mc: "70875",
    mc: "Beige Brown"
  },
  {
    ref_gc: "72044",
    gc: "Dark Fleshtone",
    ref_ga: "",
    ga: "",
    ref_cit: "22-45",
    cit: "Doombull Brown",
    ref_old_cit: "61-18",
    old_cit: "Dark Flesh",
    ref_reap: "9071",
    reap: "Chestnut Brown",
    ref_mc: "70846",
    mc: "Mahog. Brown"
  },
  {
    ref_gc: "72045",
    gc: "Charred Brown",
    ref_ga: "72745",
    ga: "Charred Brown",
    ref_cit: "21-23",
    cit: "Dryad Bark",
    ref_old_cit: "61-12",
    old_cit: "Scorched Brown",
    ref_reap: "9028",
    reap: "Muddy Brown",
    ref_mc: "70822",
    mc: "German Cam."
  },
  {
    ref_gc: "72045",
    gc: "Charred Brown",
    ref_ga: "72745",
    ga: "Charred Brown",
    ref_cit: "21-22",
    cit: "Rinox Hide",
    ref_old_cit: "61-12",
    old_cit: "Scorched Brown",
    ref_reap: "9028",
    reap: "Muddy Brown",
    ref_mc: "70822",
    mc: "German Cam."
  },
  {
    ref_gc: "72046",
    gc: "Glacier Blue",
    ref_ga: "",
    ga: "",
    ref_cit: "22-56",
    cit: "Ulthuan Grey",
    ref_old_cit: "61-36",
    old_cit: "Ice Blue",
    ref_reap: "9063",
    reap: "Ghost White",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72047",
    gc: "Wolf Grey",
    ref_ga: "72747",
    ga: "Wolf Grey",
    ref_cit: "22-68",
    cit: "Fenrisian Grey",
    ref_old_cit: "61-49",
    old_cit: "Space Wolves Gr.",
    ref_reap: "9021",
    reap: "Snow Shadow",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72048",
    gc: "Sombre Grey",
    ref_ga: "72748",
    ga: "Sombre Grey*",
    ref_cit: "21-32",
    cit: "The Fang",
    ref_old_cit: "61-48",
    old_cit: "Shadow Grey",
    ref_reap: "9020",
    reap: "Twilight Blue",
    ref_mc: "70964",
    mc: "Field Blue"
  },
  {
    ref_gc: "72049",
    gc: "Stonewall Grey",
    ref_ga: "72749",
    ga: "Stonewall Grey",
    ref_cit: "22-50",
    cit: "Administrat.Grey",
    ref_old_cit: "61-53",
    old_cit: "Fortress Grey",
    ref_reap: "9087",
    reap: "Weath. Stone",
    ref_mc: "70907",
    mc: "Pale Grey Blue"
  },
  {
    ref_gc: "72050",
    gc: "Cold Grey",
    ref_ga: "72750",
    ga: "Cold Grey",
    ref_cit: "22-49",
    cit: "Dawnstone",
    ref_old_cit: "61-52",
    old_cit: "Codex Grey",
    ref_reap: "9038",
    reap: "Rainy Grey",
    ref_mc: "70869",
    mc: "Basalt Grey"
  },
  {
    ref_gc: "72051",
    gc: "Black",
    ref_ga: "72751",
    ga: "Black",
    ref_cit: "21-25",
    cit: "Abaddon Black",
    ref_old_cit: "61-51",
    old_cit: "Chaos Black",
    ref_reap: "9037",
    reap: "Pure Black",
    ref_mc: "70950",
    mc: "Black"
  },
  {
    ref_gc: "72052",
    gc: "Silver",
    ref_ga: "72752",
    ga: "Silver",
    ref_cit: "22-60",
    cit: "Runefang Steel",
    ref_old_cit: "61-55",
    old_cit: "Mithril Silver",
    ref_reap: "9054",
    reap: "Polished Silver",
    ref_mc: "70997",
    mc: "Silver"
  },
  {
    ref_gc: "72053",
    gc: "Chain Mail",
    ref_ga: "72753",
    ga: "Chain Mail",
    ref_cit: "22-59",
    cit: "Ironbreaker",
    ref_old_cit: "61-56",
    old_cit: "Chainmail",
    ref_reap: "9053",
    reap: "Honed Steel",
    ref_mc: "70865",
    mc: "Oily Steel"
  },
  {
    ref_gc: "72054",
    gc: "Gun metal",
    ref_ga: "",
    ga: "",
    ref_cit: "21-28",
    cit: "Leadbelcher",
    ref_old_cit: "61-57",
    old_cit: "Boltgun Metal",
    ref_reap: "9052",
    reap: "Shadowed Steel",
    ref_mc: "70863",
    mc: "Gunmetal Grey"
  },
  {
    ref_gc: "72055",
    gc: "Polished Gold",
    ref_ga: "72755",
    ga: "Polished Gold",
    ref_cit: "22-62",
    cit: "Auric Arm. Gold",
    ref_old_cit: "61-62",
    old_cit: "Burnished Gold",
    ref_reap: "9051",
    reap: "New Gold",
    ref_mc: "70996",
    mc: "Gold"
  },
  {
    ref_gc: "72056",
    gc: "Glorious Gold",
    ref_ga: "72756",
    ga: "Glorious Gold",
    ref_cit: "22-61",
    cit: "Gehenna's Gold",
    ref_old_cit: "61-63",
    old_cit: "Shining Gold",
    ref_reap: "9050",
    reap: "Antique Gold",
    ref_mc: "70996",
    mc: "Gold"
  },
  {
    ref_gc: "72057",
    gc: "Bright Bronze",
    ref_ga: "72757",
    ga: "Bright Bronze",
    ref_cit: "21-30",
    cit: "Screaming Bell",
    ref_old_cit: "",
    old_cit: "",
    ref_reap: "",
    reap: "",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72057",
    gc: "Bright Bronze",
    ref_ga: "72757",
    ga: "Bright Bronze",
    ref_cit: "22-63",
    cit: "Hashut Copper",
    ref_old_cit: "61-60",
    old_cit: "Dwarf Bronze",
    ref_reap: "9049",
    reap: "Ancient Bronze",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72058",
    gc: "Brassy Brass",
    ref_ga: "",
    ga: "",
    ref_cit: "22-65",
    cit: "Brass Scorpion",
    ref_old_cit: "61-61",
    old_cit: "Brazen Brass",
    ref_reap: "",
    reap: "",
    ref_mc: "70999",
    mc: "Copper"
  },
  {
    ref_gc: "72059",
    gc: "Ham. Copper",
    ref_ga: "",
    ga: "",
    ref_cit: "21-29",
    cit: "Balthazar Gold",
    ref_old_cit: "",
    old_cit: "",
    ref_reap: "9102",
    reap: "Coppery Orange",
    ref_mc: "70999",
    mc: "Copper"
  },
  {
    ref_gc: "72060",
    gc: "Tinny Tin",
    ref_ga: "",
    ga: "",
    ref_cit: "21-31",
    cit: "WarplockBronze",
    ref_old_cit: "61-58",
    old_cit: "Tin Bitz",
    ref_reap: "9125",
    reap: "Scorched Metal",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72061",
    gc: "Khaki",
    ref_ga: "",
    ga: "",
    ref_cit: "21-16",
    cit: "Zandri Dust",
    ref_old_cit: "61-82",
    old_cit: "Komm. Khaki",
    ref_reap: "9122",
    reap: "Terran Khaki",
    ref_mc: "70821",
    mc: "G. Cam. Yellow"
  },
  {
    ref_gc: "72061",
    gc: "Khaki",
    ref_ga: "",
    ga: "",
    ref_cit: "22-35",
    cit: "Karak Stone",
    ref_old_cit: "61-82",
    old_cit: "Komm. Khaki",
    ref_reap: "9122",
    reap: "Terran Khaki",
    ref_mc: "70821",
    mc: "G. Cam. Yellow"
  },
  {
    ref_gc: "72062",
    gc: "Earth",
    ref_ga: "72762",
    ga: "Earth",
    ref_cit: "21-17",
    cit: "Steel Leg. Drab",
    ref_old_cit: "61-81",
    old_cit: "Graveyard Earth",
    ref_reap: "9127",
    reap: "Uniform Brown",
    ref_mc: "70921",
    mc: "English Unif."
  },
  {
    ref_gc: "72063",
    gc: "Desert Yellow",
    ref_ga: "72763",
    ga: "Desert Yellow",
    ref_cit: "22-34",
    cit: "Tallarn Sand",
    ref_old_cit: "61-83",
    old_cit: "Desert Yellow",
    ref_reap: "9129",
    reap: "Faded Khaki",
    ref_mc: "70923",
    mc: "Japan Unif. WWII"
  },
  {
    ref_gc: "72065",
    gc: "Terracotta",
    ref_ga: "",
    ga: "",
    ref_cit: "22-46",
    cit: "Tuskgor Fur",
    ref_old_cit: "61-80",
    old_cit: "Terracotta",
    ref_reap: "9134",
    reap: "Clotted Red",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72066",
    gc: "Tan",
    ref_ga: "",
    ga: "",
    ref_cit: "21-18",
    cit: "Bugmans Glow",
    ref_old_cit: "61-79",
    old_cit: "Tanned Flesh",
    ref_reap: "9139",
    reap: "Antique Rose",
    ref_mc: "70818",
    mc: "Red Leather"
  },
  {
    ref_gc: "72067",
    gc: "Cayman Green",
    ref_ga: "",
    ga: "",
    ref_cit: "21-14",
    cit: "Castellan Green",
    ref_old_cit: "61-84",
    old_cit: "Catachan Green",
    ref_reap: "9139",
    reap: "Muddy Olive",
    ref_mc: "70897",
    mc: "Bronce Green"
  },
  {
    ref_gc: "72106",
    gc: "Scarlett Red",
    ref_ga: "",
    ga: "",
    ref_cit: "21-04",
    cit: "Khorne Red",
    ref_old_cit: "61-04",
    old_cit: "Scab Red",
    ref_reap: "9002",
    reap: "Deep Red",
    ref_mc: "70908",
    mc: "Carmine Red"
  },
  {
    ref_gc: "72140",
    gc: "Heavy Skint.",
    ref_ga: "",
    ga: "",
    ref_cit: "22-36",
    cit: "Cadian Fleshtone",
    ref_old_cit: "68-06",
    old_cit: "Tallarn Flesh",
    ref_reap: "9030",
    reap: "Leather Brown",
    ref_mc: "70843",
    mc: "Cork Brown"
  },
  {
    ref_gc: "72141",
    gc: "Heavy Red",
    ref_ga: "",
    ga: "",
    ref_cit: "21-03",
    cit: "Mephiston Red",
    ref_old_cit: "68-01",
    old_cit: "Mechrite Red",
    ref_reap: "9134",
    reap: "Clotted Red",
    ref_mc: "70926",
    mc: "Red Leather"
  },
  {
    ref_gc: "72142",
    gc: "Heavy Violet",
    ref_ga: "",
    ga: "",
    ref_cit: "21-05",
    cit: "Naggaroth Night",
    ref_old_cit: "",
    old_cit: "",
    ref_reap: "9079",
    reap: "Deep Amethyst",
    ref_mc: "70960",
    mc: "Violeta"
  },
  {
    ref_gc: "72143",
    gc: "Heavy Blue",
    ref_ga: "",
    ga: "",
    ref_cit: "21-08",
    cit: "Macragge Blue",
    ref_old_cit: "68-07",
    old_cit: "Mordian Blue",
    ref_reap: "9055",
    reap: "Breonne Blue",
    ref_mc: "70965",
    mc: "Prussian Blue"
  },
  {
    ref_gc: "72144",
    gc: "Heavy Bluegrey",
    ref_ga: "",
    ga: "",
    ref_cit: "21-26",
    cit: "Celestra Grey",
    ref_old_cit: "68-11",
    old_cit: "Astrono. Grey",
    ref_reap: "9087",
    reap: "Weath. Stone",
    ref_mc: "70905",
    mc: "Blue Grey Pale"
  },
  {
    ref_gc: "72145",
    gc: "Heavy Grey",
    ref_ga: "",
    ga: "",
    ref_cit: "21-24",
    cit: "Mechanicus SG",
    ref_old_cit: "68-10",
    old_cit: "Adeptus Battlegr.",
    ref_reap: "9176",
    reap: "Military Green",
    ref_mc: "70924",
    mc: "Russian Unif."
  },
  {
    ref_gc: "72146",
    gc: "Heavy Green",
    ref_ga: "",
    ga: "",
    ref_cit: "22-27",
    cit: "Loren Forest",
    ref_old_cit: "68-13",
    old_cit: "Knarloc Green",
    ref_reap: "9158",
    reap: "Olive Drab",
    ref_mc: "70823",
    mc: "German Cam."
  },
  {
    ref_gc: "72147",
    gc: "H. Black Green",
    ref_ga: "",
    ga: "",
    ref_cit: "21-12",
    cit: "Caliban Green",
    ref_old_cit: "68-12",
    old_cit: "Orkhide Shade",
    ref_reap: "9082",
    reap: "Jungle Moss",
    ref_mc: "70980",
    mc: "Black Green"
  },
  {
    ref_gc: "72148",
    gc: "Heavy Warmg.",
    ref_ga: "",
    ga: "",
    ref_cit: "21-27",
    cit: "Rakath Flesh",
    ref_old_cit: "68-18",
    old_cit: "Dheneb Stone",
    ref_reap: "9109",
    reap: "Ruddy Leather",
    ref_mc: "",
    mc: ""
  },
  {
    ref_gc: "72149",
    gc: "Heavy Kakhi",
    ref_ga: "",
    ga: "",
    ref_cit: "21-15",
    cit: "Death W. Forest",
    ref_old_cit: "68-14",
    old_cit: "Gretchin-Green",
    ref_reap: "9159",
    reap: "Worn Olive",
    ref_mc: "70882",
    mc: "Middlestone"
  },
  {
    ref_gc: "72150",
    gc: "Heavy Ocre",
    ref_ga: "",
    ga: "",
    ref_cit: "",
    cit: "",
    ref_old_cit: "69-03",
    old_cit: "Taupset Ochre",
    ref_reap: "9204",
    reap: "Half Orc Highl.",
    ref_mc: "70856",
    mc: "Ochre Brown"
  },
  {
    ref_gc: "72151",
    gc: "Heavy Gold Br.",
    ref_ga: "",
    ga: "",
    ref_cit: "21-01",
    cit: "Averland Sunset",
    ref_old_cit: "68-04",
    old_cit: "Lyand. Darksun",
    ref_reap: "9128",
    reap: "Green Ocre",
    ref_mc: "70877",
    mc: "Gold Brown"
  },
  {
    ref_gc: "72153",
    gc: "Heavy Brown",
    ref_ga: "",
    ga: "",
    ref_cit: "22-48",
    cit: "Baneblad. Brown",
    ref_old_cit: "68-17",
    old_cit: "Khemri Brown",
    ref_reap: "9160",
    reap: "Woodst. Brown",
    ref_mc: "70983",
    mc: "Flat Earth"
  },
  {
    ref_gc: "72154",
    gc: "Heavy Sienna",
    ref_ga: "",
    ga: "",
    ref_cit: "",
    cit: "",
    ref_old_cit: "68-16",
    old_cit: "Flat Brown",
    ref_reap: "9042",
    reap: "Dark Highlight",
    ref_mc: "70984",
    mc: "Flat Brown"
  },
  {
    ref_gc: "72155",
    gc: "H. Charcoal",
    ref_ga: "",
    ga: "",
    ref_cit: "22-55",
    cit: "Stormvermin Fur",
    ref_old_cit: "68-15",
    old_cit: "Charadon Granite",
    ref_reap: "9037",
    reap: "Pure Black",
    ref_mc: "70950",
    mc: "Black"
  }
]

export default equiv;
